### ISSUE TITLE
Add about networking and network protocols

### ISSUE THREAD

**Issue by Sleep-lover** [shhossain/computer_science#137]
I am interested in adding more about networking and network protocols.

**Comment by Sleep-lover** [comment]
Hay! @shhossain can you please assign this issue to me

**Comment by Sleep-lover** [comment]
Thanks for such a quick response and also can u add  hacktoberfest tag on it

**Comment by shhossain** [comment]
@Sleep-lover your PR must be over 100 unique additions to get hacktoberfest-accepted label in your PR

**Comment by rishiwardhan** [comment]
hi @shhossain i like to add new materials to networking and network protocols

**Comment by shhossain** [comment]
@rishiwardhan @Sleep-lover already has been assigned to this issue. If @Sleep-lover don't add it you will be assigned. Or if @Sleep-lover PR is not completed you can add additional info to it.

**Comment by rishiwardhan** [comment]
@shhossain i have completed the issue and created a pull request please approve it.

**Comment by shhossain** [comment]
@rishiwardhan @Sleep-lover both of your PRs are merged.
