### ISSUE TITLE
Adding about Pointers

### ISSUE THREAD

**Issue by deepshikha2708** [shhossain/computer_science#148]
can you assign me this issue? Please tell me where do I add this topic in.

**Comment by shhossain** [comment]
Not sure which section should pointers belong to. Maybe programming language. You research online, should pointer belong to an existing section or have to create new section. I am assigning you this issue.

**Comment by rishiwardhan** [comment]
@shhossain how much we should add to get hactoberfest label ?

**Comment by shhossain** [comment]
@rishiwardhan i've already added your hacktoberfest accepted label in your recent pr.

**Comment by rishiwardhan** [comment]
Then ok thanks for giving this opportunity

**Comment by shhossain** [comment]
@rishiwardhan to get more you must add similar numbers of additions
