### ISSUE TITLE
Spelling issue in README

### ISSUE THREAD

**Issue by UperscuzziSchoolAcc** [shhossain/computer_science#151]
In the description on the XOR operator, "different" is spelled "diffrent"

**Comment by Atharv-Nalwade** [comment]
Ok I got that I will do it can I get assigned to this issue also that would mark my first hacktoberfest contribution

**Comment by Sabine91** [comment]
for getting the hacktoberfest tag u need to contribute atleast 100+ lines of code or content to the repo, just correcting the spelling wont work.

**Comment by Atharv-Nalwade** [comment]
I have just done the task and created a pull request
 I am new to open source so can anyone tell me how the flow of getting pull req. happens 
 Also @Sabine91 can you see my pull request and I am seeing 
 Review required and merging is blocked what does that mean

**Comment by Sabine91** [comment]
see the process works like this,
You first review and understand the repo/project structure and then either find problems/bugs/issues or contribute something new to it, u can do this by either editing the file with the issue or just create a new file if u want to add something.
 
Step 1: Fork the repository
Step 2: Edit the forked repository.
Step 3: Then when you will create a pull request it will show the differences between your forked repository and the main/origin branch of that original repository.

In small words you have to do all the changes and addition by creating a fork of the main repo on your profile, edit the repo on your profile and then create a pull request.

Now once you have opened a PR, someone either the maintainer or the moderator will have to review it before it can be merged to the main branch, they can either ask you to change a few things or just approve it and merge it in the main branch.

**Comment by Sabine91** [comment]
What you should do to solve this issue.

Go to the readme and click the edit file icon, it will automatically fork the repo for you, correct the spelling and then open a PR.
