### ISSUE TITLE
Link Error 404: computer_science/CONTRIBUTING.md

### ISSUE THREAD

**Issue by mdfaizanahmed786** [shhossain/computer_science#23]
### Broken Links in the following sections:
**Getting started**

1. the introduction to working in the docs repository
2. the  GitHub Markdown reference
3. types of contributions

**Issues**

1. existing issues
2. labels

**Make changes in the UI**

1. working in a codespace

#### Make changes locally

1. the development guide

 **Commit your update**

1. self-review

**Your PR is merged!**

1. contribute to the docs

**Comment by shhossain** [comment]
Can you fix it? If you can then submit a pull request.

**Comment by mdfaizanahmed786** [comment]
Sure, I'll try to fix it.

**Comment by mdfaizanahmed786** [comment]
Hey there, I've created a pull request. You can review it and proceed.

**Comment by shhossain** [comment]
#25 Is merged.
