### ISSUE TITLE
updating readme file for hash table

### ISSUE THREAD

**Issue by Sangjukta3011** [shhossain/computer_science#337]
The content in Hash Table folder seems very insufficient to explain the whole topic. So, i would like to contribute by putting some more information about the same.

**Comment by shhossain** [comment]
@Sangjukta3011 sure. Assigning this issue to you.

**Comment by rohankaushal123** [comment]
@shhossain I caan do that I guess he is unavailable , I will do this issue and will resolve the problem !

**Comment by shhossain** [comment]
@rohankaushal123 sure.

**Comment by rohankaushal123** [comment]
I've added the content for Hashtable and raised the PR
Please review and accept and can close the issue !
I will look for some more issues raised and will complete and raise further
PR's

**Comment by shhossain** [comment]
#678
