### ISSUE TITLE
Adding more content about Object Based Models in DBMS folder

### ISSUE THREAD

**Issue by sahooabhipsa10** [shhossain/computer_science#367]
I checked out your DBMS Folder and noticed that it has information about the Record Based data Models such as Relational, Network and Hierarchical Models but doesn't have any information about  the Object based models such as the entity-relationship model, object-oriented model, the semantic data model, the functional data model. I would like to edit this in and elaborate more on this topic.

**Comment by shhossain** [comment]
@sahooabhipsa10 sure.

**Comment by rohankaushal123** [comment]
@shhossain Please assign it to me , I'll do it !

**Comment by shhossain** [comment]
@rohankaushal123 would you like to add more or should i close it?

**Comment by rohankaushal123** [comment]
You can close the issue
