### ISSUE TITLE
Pull request...

### ISSUE THREAD

**Issue by Francesco601** [shhossain/computer_science#618]
I don't want to seem pushy, but I would appreciate if someone would take a look at my pull request. If it is too long or there is some problem, please let me know so I can revise it, improve or whatever you prefer. By the way, thank you to the creator and tll the contributors for this well done repository! It has inspired me to do some of my own things that may be of help to people learning computer science.

**Comment by shhossain** [comment]
@Francesco601, I apologize for the delay in responding to your pull request. I was occupied with my studies and couldn't address it promptly. I did notice the pull request, but unfortunately, there seems to be a merge conflict with it. This typically occurs when you have an outdated version of the repository forked.

Usually, I encourage contributors to fix merge conflicts themselves as it can be a valuable learning experience. I regret not informing you earlier about the conflict. However, if you require any assistance in resolving the merge conflict, please don't hesitate to reach out to me. I'd be happy to help you with it.

**Comment by Francesco601** [comment]
Ok, I'll see if I can fix it myself.

**Comment by Francesco601** [comment]
Ok, it said "resolved successfully."

**Comment by Francesco601** [comment]
Ok, I just need to touch up a few things, but it's done.
