### ISSUE TITLE
Description of UDP is missing

### ISSUE THREAD

**Issue by manavmittal05** [shhossain/computer_science#641]
**Problem**
Information about User Datagram Protocol (UDP) is missing from Networking.
**Solution I propose**
I want to add a complete description of UDP, the structure of packets and its application in networking.

**Comment by arpitasen20** [comment]
can i work on this issue?

**Comment by shhossain** [comment]
oka. I'm assigning this issue to you.

**Comment by manavmittal05** [comment]
Added.
