### ISSUE TITLE
Request to Add Number System Conversion Topics

### ISSUE THREAD

**Issue by ZRX-SIGMA** [shhossain/computer_science#653]
These topics could cover a range of conversions such as binary to decimal, hexadecimal to binary, or any other common conversions related to number systems. I believe that adding these topics would greatly benefit the repository's users who are looking for information and guidance on these fundamental concepts. 
Could you assign this issue to me?

**Comment by Sarthak950** [comment]
@ZRX-SIGMA  I will do this

**Comment by ZRX-SIGMA** [comment]
Bro , Let him say, I opened this issue..

**Comment by Sarthak950** [comment]
@ZRX-SIGMA sorry i thought u were the owner

**Comment by ZRX-SIGMA** [comment]
> @ZRX-SIGMA sorry i thought u were the owner 

I think we can share this issue, I can write for python, u can write in any other lang..

**Comment by Sarthak950** [comment]
i can do C, C++, JS

**Comment by ZRX-SIGMA** [comment]
Yupp, That will do.

**Comment by Sarthak950** [comment]
working on it

**Comment by ZRX-SIGMA** [comment]
@shhossain

**Comment by Sarthak950** [comment]
#656 done for C, CPP, JS, TS, Lua, Java

**Comment by Sarthak950** [comment]
@shhossain sir review this please

**Comment by shhossain** [comment]
@Sarthak950 check your PR. And I am assigning this issue to both @Sarthak950 @ZRX-SIGMA.

**Comment by Sarthak950** [comment]
@shhossain done

**Comment by Sarthak950** [comment]
@ZRX-SIGMA are u working on the python one sir

**Comment by ZRX-SIGMA** [comment]
Yess

**Comment by Sarthak950** [comment]
@shhossain #660 check this out

**Comment by shhossain** [comment]
@Sarthak950 check my review.

**Comment by Sarthak950** [comment]
i did see anything there @shhossain

**Comment by Sarthak950** [comment]
@shhossain i did not see any thing there

**Comment by shhossain** [comment]
@Sarthak950 check #660

**Comment by Sarthak950** [comment]
@shhossain yes i checked but i am not getting anything

**Comment by shhossain** [comment]
![image](https://github.com/shhossain/computer_science/assets/80335059/1d0cb98f-9b78-408d-8088-f7ba65a6be11)

**Comment by shhossain** [comment]
@Sarthak950 I've fixed the problem just now. don't need to do anything.
