### ISSUE TITLE
Would like to add more about HTTP in Networking

### ISSUE THREAD

**Issue by manavmittal05** [shhossain/computer_science#663]
I would like to explain the different versions of HTTP. How they work and how they are different what are the advantages and disadvantages of one over the other.

**Comment by rohankaushal123** [comment]
@manavmittal05 I wan to work on it 
I am a computer science student at IIT BHU and want to contribute for students 
Will add it Please assign to me

**Comment by manavmittal05** [comment]
Can you please look at some other issue because I am working on it right now. Thanks

**Comment by rohankaushal123** [comment]
I've completed it please check it out

**Comment by manavmittal05** [comment]
Great work

**Comment by shhossain** [comment]
@manavmittal05 would you like to add more or should I close the issue?

**Comment by manavmittal05** [comment]
I will add more

**Comment by shhossain** [comment]
@manavmittal05 okay.

**Comment by manavmittal05** [comment]
It is added.
