### ISSUE TITLE
Fix space and time complexity table and update divide and conquer section 

### ISSUE THREAD

**Issue by aheaton22** [shhossain/computer_science#683]
I would like to update the Divide and Conquer page, specifically the following:

- Link the example algorithms (Quicksort, Merge Sort, Closest Pair of Points,..) to existing pages. 
- Add the inversion problem as an overall example of Divide and Conquer algorithms.

**Comment by shhossain** [comment]
@aheaton22 sure.

**Comment by aheaton22** [comment]
As I was working on this issue I noticed that the 'Merge Sort Time and Space Complexity' section on the Merge Sort page is a bit hard to read.  I was going to fix it but I wonder if I should do it in a separate issue.

**Comment by shhossain** [comment]
@aheaton22 you can submit pull request no need to create new issue.

**Comment by aheaton22** [comment]
Thanks, I'll do that

**Comment by aheaton22** [comment]
changes have been merged in
