### ISSUE TITLE
Update Algorithms readme 

### ISSUE THREAD

**Issue by aheaton22** [shhossain/computer_science#714]
I’ve noticed that the Algorithm list and links on the Algorithm’s main page needs to be updated.   

**Describe the solution you'd like to add**
I would like to..
- [x] Add Space and Time complexity headers with links. 
- [x] Add a Divide and Conquer header with algorithm list.  
- [x] Add an Algorithm design header with the Sliding Window Technique
- [x] Add a String Based Algorithms header with algorithm list.  
- [x] Verify that all links work correctly.

**Comment by shhossain** [comment]
Okay.

**Comment by aheaton22** [comment]
merged in changes, closing issue
