### ISSUE TITLE
Add time complexity and Python code examples for common heap operations

### ISSUE THREAD

**Issue by mjung1** [shhossain/computer_science#756]
I noticed that the heap section (Heap.md) does not currently have time complexity analysis or code examples provided for all common heap operations.

I would like to contribute by adding the time complexity and a Python code example for each heap operation.

Given that it appears that the heap section aims to be fairly comprehensive and that other data structures (e.g. arrays, graphs, etc.) sections have time complexity analysis and code examples for their respective operations, I believe that making the aforementioned additions would be valuable.

**Comment by shhossain** [comment]
Sure
